name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Init
      run: |
        make init
    - name: Force select xcode 15.3
      run: |
        sudo xcode-select -switch /Applications/Xcode_15.3.app
    - name: Build
      run: |
        make build
    - name: SPM Build
      run: |
        make spm_build
    - name: Tests
      run: |
        make test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        flags: tests
        directory: ./CoverageReports
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - name: documentation
      if: github.ref == 'refs/heads/master'
      run: |
        make doc
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: chausovSurfStudio
        author_email: chausov@surf.dev
        message: "Updates for documentation"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
